version: '2'
services:
  pharmastatusmpm-mongodb:
    image: mongo:4.0.16
    ports:
      - '27017:27017'
    command: mongos --configdb pharmastatusmpm-mongodb-config
  pharmastatusmpm-mongodb-node:
    build:
      context: .
      dockerfile: mongodb/MongoDB.Dockerfile
    command: mongod --replSet rs1 --noprealloc --smallfiles
  pharmastatusmpm-mongodb-config:
    image: mongo:4.0.16
    container_name: pharmastatusmpm-mongodb-config
    command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
